//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGA_Havalimanı_Yönetim_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeEntities : DbContext
    {
        public ProjeEntities()
            : base("name=ProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Havayolları> Havayolları { get; set; }
        public virtual DbSet<IgaPersonel> IgaPersonel { get; set; }
        public virtual DbSet<KabinEkibi> KabinEkibi { get; set; }
        public virtual DbSet<Uçaklar> Uçaklar { get; set; }
        public virtual DbSet<Uçuşlar> Uçuşlar { get; set; }
        public virtual DbSet<YerHizmetleriPersonel> YerHizmetleriPersonel { get; set; }
        public virtual DbSet<Yolcu> Yolcu { get; set; }
    }
}
