//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGA_Havalimanı_Yönetim_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uçaklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uçaklar()
        {
            this.Uçuşlar = new HashSet<Uçuşlar>();
        }
    
        public int UçakID { get; set; }
        public int HavayoluID { get; set; }
        public string ModelNo { get; set; }
        public string Üretici { get; set; }
    
        public virtual Havayolları Havayolları { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uçuşlar> Uçuşlar { get; set; }
    }
}
