//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGA_Havalimanı_Yönetim_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uçuşlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uçuşlar()
        {
            this.KabinEkibi = new HashSet<KabinEkibi>();
            this.Yolcu = new HashSet<Yolcu>();
        }
    
        public int UçuşID { get; set; }
        public int UçakID { get; set; }
        public string KalkışTarih { get; set; }
        public string KalkışSaat { get; set; }
        public string İnişTarih { get; set; }
        public string İnişSaat { get; set; }
        public string KalkışKonum { get; set; }
        public string İnişKonum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KabinEkibi> KabinEkibi { get; set; }
        public virtual Uçaklar Uçaklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yolcu> Yolcu { get; set; }
    }
}
